---
- hosts: 172.3.6.109
  become: yes
  tasks: 
   - name: i want to execute direct linux
     command: hostname -f
     register: myresult

   - name: i want to display my first result 
     debug: 
         msg:"{{myresult}}"
         
