---
- hosts: 172.31.6.109
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: copy file into node side
    copy:
       src: mytestfile
       dest: /home/ubuntu/mytestfile

  - name: i want to install webserver on ansible nodes side
    apt:
     name: apache2
     state: present
 
  - name: i want to copy index file into ansible node side
    template:
       src: mydynamicfile.j2
       dest: /var/www/html/index.html
  - name: i want to download internet files
    get_url:
      url: https://archive.apache.org/dist/tomcat/tomcat-11/v11.0.0-M6/bin/apache-tomcat-11.0.0-M6.tar.gz.asc
      dest: /home/ubuntu/apache-tomcat-10.0.20.tar.gz
      force_basic_auth: yes 


       

